#!/bin/bash

# Couleur verte pour l'affichage du texte
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # Reset de la couleur

# Demander à l'utilisateur de choisir entre "prod" ou "qual"
if [ "$1" = "prod" ]; then
    echo -e "${RED}Vous avez choisi 'prod'.${NC}"
    version_checkmk="1.2.3"  # Remplacez "1.2.3" par le numéro de version Checkmk réel
    container_name="monitoring_prod_$version_checkmk"
    volume_name="monitoring_data_prod_$version_checkmk"
    run_command="docker run --name $container_name -p 8080:80 -v $volume_name:/checkmk_data nouvelle_version_checkmk"
else
    echo -e "${GREEN}Vous avez choisi 'qual'.${NC}"
    version_checkmk="4.5.6"  # Remplacez "4.5.6" par le numéro de version Checkmk réel
    container_name="monitoring_qual_$version_checkmk"
    volume_name="monitoring_data_qual_$version_checkmk"
    run_command="docker run --name $container_name -p 8081:80 -v $volume_name:/checkmk_data nouvelle_version_checkmk"
fi

echo -e "${GREEN}Version de Checkmk : $version_checkmk${NC}"

# Étape 3 : Copier l'ancien volume vers le nouveau volume
echo -e "${GREEN}Étape 3 : Copie de l'ancien volume vers le nouveau volume${NC}"
docker run --rm -v monitoring_data_source:/source -v "$volume_name":/destination alpine cp -a /source/. /destination
if [ $? -eq 0 ]; then
    echo -e "${GREEN}La copie de l'ancien volume vers le nouveau volume a été effectuée avec succès.${NC}"
else
    echo -e "${GREEN}Une erreur s'est produite lors de la copie de l'ancien volume vers le nouveau volume.${NC}"
    exit 1
fi

# Étape 4 : Exécuter le nouveau conteneur avec la nouvelle version de Checkmk
echo -e "${GREEN}Étape 4 : Exécution du nouveau conteneur avec la nouvelle version de Checkmk${NC}"
eval "$run_command"
if [ $? -eq 0 ]; then
    echo -e "${GREEN}Le nouveau conteneur a été exécuté avec succès.${NC}"
else
    echo -e "${GREEN}Une erreur s'est produite lors de l'exécution du nouveau conteneur.${NC}"
    exit 1
fi

# Étape 5 : Vérification de la mise à jour
echo -e "${GREEN}Étape 5 : Vérification de la mise à jour"
# Ajoutez ici vos étapes de vérification supplémentaires
echo -e "Veuillez effectuer les vérifications nécessaires.${NC}"

# Étape 6 : Nettoyage des ressources inutilisées
echo -e "${GREEN}Étape 6 : Nettoyage des ressources inutilisées"
# Ajoutez ici vos étapes de nettoyage supplémentaires
echo -e "Veuillez effectuer le nettoyage approprié.${NC}"

echo -e "${GREEN}La mise à jour de la version Docker de Checkmk a été effectuée avec succès.${NC}"
